DROP TABLE IF EXISTS OFFER;
DROP TABLE IF EXISTS APPLICATION;
DROP TABLE IF EXISTS JOB_ELIGIBILITY;
DROP TABLE IF EXISTS JOB;
DROP TABLE IF EXISTS COMPANY;
DROP TABLE IF EXISTS ACADEMIC_RECORD;
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS PROGRAM;

CREATE TABLE PROGRAM (
    program_id INTEGER PRIMARY KEY AUTOINCREMENT,
    program_name TEXT NOT NULL,
    department TEXT NOT NULL
);

CREATE TABLE STUDENT (
    student_id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    program_id INTEGER,
    FOREIGN KEY (program_id) REFERENCES PROGRAM(program_id) ON DELETE SET NULL
);

CREATE TABLE ACADEMIC_RECORD (
    record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER UNIQUE NOT NULL,
    cgpa REAL NOT NULL CHECK(cgpa >= 0.0 AND cgpa <= 10.0),
    active_backlogs INTEGER DEFAULT 0,
    tenth_percentage REAL,
    twelfth_percentage REAL,
    FOREIGN KEY (student_id) REFERENCES STUDENT(student_id) ON DELETE CASCADE
);

CREATE TABLE COMPANY (
    company_id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_name TEXT NOT NULL,
    industry TEXT,
    contact_email TEXT,
    location TEXT
);

CREATE TABLE JOB (
    job_id INTEGER PRIMARY KEY AUTOINCREMENT,
    company_id INTEGER NOT NULL,
    job_title TEXT NOT NULL,
    job_description TEXT,
    package_lpa REAL NOT NULL,
    drive_date DATE,
    FOREIGN KEY (company_id) REFERENCES COMPANY(company_id) ON DELETE CASCADE
);

CREATE TABLE JOB_ELIGIBILITY (
    eligibility_id INTEGER PRIMARY KEY AUTOINCREMENT,
    job_id INTEGER UNIQUE NOT NULL,
    min_cgpa REAL DEFAULT 6.0,
    max_backlogs_allowed INTEGER DEFAULT 0,
    FOREIGN KEY (job_id) REFERENCES JOB(job_id) ON DELETE CASCADE
);

CREATE TABLE APPLICATION (
    app_id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    job_id INTEGER NOT NULL,
    application_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'APPLIED' CHECK(status IN ('APPLIED', 'SHORTLISTED', 'REJECTED', 'OFFERED')),
    UNIQUE(student_id, job_id),
    FOREIGN KEY (student_id) REFERENCES STUDENT(student_id) ON DELETE CASCADE,
    FOREIGN KEY (job_id) REFERENCES JOB(job_id) ON DELETE CASCADE
);

CREATE TABLE OFFER (
    offer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    app_id INTEGER UNIQUE NOT NULL,
    offer_letter_code TEXT UNIQUE NOT NULL,
    offered_salary_lpa REAL NOT NULL,
    joining_date DATE,
    FOREIGN KEY (app_id) REFERENCES APPLICATION(app_id) ON DELETE CASCADE
);